build container:
  tags: [ato_buildbox]
  script:
    - now=$(echo $CI_PIPELINE_CREATED_AT | tr :T - | head -c 19)
    - podman system prune -af
    - podman build -t registry.gitlab.pxeger.com/attempt-this-online/attempt-this-online -t registry.gitlab.pxeger.com/attempt-this-online/attempt-this-online:$now .
    - podman login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin <<< "$CI_REGISTRY_PASSWORD"
    - podman push registry.gitlab.pxeger.com/attempt-this-online/attempt-this-online registry.gitlab.pxeger.com/attempt-this-online/attempt-this-online:$now

run tests:
  needs: [build container]
  tags: [ato_buildbox]
  script:
    - now=$(echo $CI_PIPELINE_CREATED_AT | tr :T - | head -c 19)
    - sudo podman run --rm --privileged --cgroupns private -v ato_images:/mnt registry.gitlab.pxeger.com/attempt-this-online/attempt-this-online:$now true
    - sudo podman run --rm --detach --name ato -p 127.0.0.1:8500:8500 --privileged --cgroupns private -v ato_images:/mnt registry.gitlab.pxeger.com/attempt-this-online/attempt-this-online:$now
    - sudo podman logs -f ato &
    - URL='ws://127.0.0.1:8500/api/v1/ws/execute' test/run
  after_script:
    - sudo podman stop ato
    - sudo podman volume rm ato_images
