ci:
  autoupdate_schedule: quarterly
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
- repo: https://github.com/attempt-this-online/pre-commit-hooks
  rev: v0.2.0
  hooks:
  - id: runners-executable
- repo: https://github.com/pxeger/pre-commit-rust
  rev: v1.3.0
  hooks:
  - id: fmt
