ci:
  autoupdate_schedule: quarterly
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
- repo: https://github.com/attempt-this-online/pre-commit-hooks
  rev: v0.2.0
  hooks:
  - id: runners-executable
- repo: https://github.com/Young-Naive-Simple/pre-commit-rust
  rev: 3a8de64acc969112746489e5ec1f0b13e00d871e
  hooks:
  - id: fmt
