#!/bin/sh -e
# Build a package to be used by the setup script when installing.

rm -rf dist
mkdir -p dist/attempt_this_online

echo Building frontend... >&2
cd frontend
# clean up previous build artefacts; otherwise nothing seems to properly update
rm -rf .next out
npm run build
cd ..

echo Compiling binaries... >&2
cargo build --release
gcc -Wall -Werror -static yargs.c -o dist/attempt_this_online/yargs

echo Building tarball... >&2
cp target/release/sandbox target/release/server dist/attempt_this_online/
# list images
jq -r '.[].image' < languages.json | sort -u > dist/attempt_this_online/images.txt
cp -R frontend/out dist/attempt_this_online/public
cp -R \
    setup/ \
    runners/ \
    dist/attempt_this_online/
cd dist
tar -czf attempt_this_online.tar.gz attempt_this_online
