#!/bin/sh -e
# Build a package to be used by the setup script when installing.

rm -rf dist
mkdir -p dist/attempt_this_online

echo Building frontend... >&2
cd frontend
# clean up previous build artefacts; otherwise nothing seems to properly update
rm -rf .next out
npm run build
cd ..

echo Compiling binaries... >&2
cd backend
go build -o ../dist/attempt_this_online/server server.go
cd ..
gcc -Wall -Werror wrapper.c -static -lrt -lpthread -o dist/attempt_this_online/wrapper
gcc -Wall -Werror -static yargs.c -o dist/attempt_this_online/yargs

echo Building tarball... >&2
# list images
cd backend
go run listImages.go > ../dist/attempt_this_online/images.txt
cd ..
cp -R frontend/out dist/attempt_this_online/public
cp -R \
    setup/ \
    sandbox \
    runners/ \
    dist/attempt_this_online/
cd dist
tar -czf attempt_this_online.tar.gz attempt_this_online
