volumes:
  images:
services:
  backend:
    # explicitly specify platform so this can work with Docker Desktop on ARM
    platform: linux/amd64
    build: .
    develop:
      watch:
        - path: ./target/x86_64-unknown-linux-gnu/debug/attempt-this-online
          action: sync+restart
          target: /usr/local/lib/ATO/server
        - path: ./runners
          action: sync
          target: /usr/local/share/ATO/runners
    volumes:
      - images:/mnt
    ports:
      - 127.0.0.1:8500:8500
    privileged: true
    cgroup: private
    command: setpriv --reuid ato --regid ato --init-groups /usr/local/lib/ATO/server
