#!/bin/sh -e
# Build a package to be used by the setup script when installing.

rm -rf build

cd api
python -m poetry update
cd ..

mkdir -p build/attempt_this_online
cd build

gcc -Wall -Werror -static ../wrapper.c -o attempt_this_online/wrapper
gcc -Wall -Werror -static ../yargs.c -o attempt_this_online/yargs

echo Building tarball... >&2
cp -R ../public ../api ../setup ../sandbox ../runners attempt_this_online/
tar -czf attempt_this_online.tar.gz attempt_this_online
