#!/bin/sh -e
# Build a package to be used by the setup script when installing.

rm -rf dist
mkdir -p dist/attempt_this_online

cd api
python -m poetry update
cd ..

echo Building frontend... >&2
cd frontend
npm run build
cd ..

echo Compiling binaries... >&2
gcc -Wall -Werror wrapper.c -static -lrt -lpthread -o dist/attempt_this_online/wrapper
gcc -Wall -Werror -static yargs.c -o dist/attempt_this_online/yargs

echo Building tarball... >&2
cp -R frontend/out dist/attempt_this_online/public
cp -R api setup sandbox runners dist/attempt_this_online/
cd dist
tar -czf attempt_this_online.tar.gz attempt_this_online
