#!/usr/bin/python
"""generate lines for /etc/fstab to automatically mount overlayfs roots
Futher information:
- fstab(5)
- https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#multiple-lower-layers
- https://wiki.archlinux.org/index.php/Overlay_filesystem
"""
import json
import os
import sys

manifest = sys.argv[1]

with open("/var/cache/ATO/images/" + manifest) as f:
    layers = json.load(f)[0]["Layers"]

# TODO: does this need to be reversed?
layers = ":".join("/usr/local/lib/ATO/layers/" + layer.removesuffix("/layer.tar") for layer in layers[::-1])

image = manifest.removeprefix("manifest_").removesuffix(".json")

# Create mount point
os.makedirs(f"/usr/local/lib/ATO/rootfs/{image}", exist_ok=True)

# The final layer "/usr/local/share/ATO/overlayfs_upper" is needed to allow bwrap to mount a tmpfs etc. there. See
# https://github.com/containers/bubblewrap/issues/413 for more info
print(f"overlay /usr/local/lib/ATO/rootfs/{image} overlay lowerdir=/usr/local/share/ATO/overlayfs_upper:{layers} 0 0")
