#!/usr/bin/python
"""generate lines for /etc/fstab to automatically mount overlayfs roots
Futher information:
- fstab(5)
- https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#multiple-lower-layers
- https://wiki.archlinux.org/index.php/Overlay_filesystem
"""
import json
import os
import sys

image = sys.argv[1]

with open("/var/cache/ATO/images/manifest.json") as f:
    layers = json.load(f)[0]["Layers"]


def dedup(a):
    s = set()
    for i in a:
        if i in s:
            continue
        else:
            s.add(i)
            yield i


layers = ":".join("/usr/local/lib/ATO/layers/" + layer.removesuffix(".tar") for layer in dedup(layers[::-1]))

# Create mount point
os.makedirs(f"/usr/local/lib/ATO/rootfs/{image}", exist_ok=True)

# The final layer "/usr/local/share/ATO/overlayfs_upper" is needed to allow the sandbox to mount a tmpfs etc. there
print(f"overlay /usr/local/lib/ATO/rootfs/{image} overlay lowerdir=/usr/local/share/ATO/overlayfs_upper:{layers} 0 0")
