#!/usr/bin/python
# Put environment variables from `skopeo inspect` into a file for `invoke` to apply to processes using this image
import json
import sys

for string in json.load(sys.stdin)["Env"]:
    sys.stdout.write(string + "\0")
