#!/bin/sh

set -e

VERSION="0.1.12"

error() {
    echo "$@" >&2; exit 2
}

# make sure this is arch linux
# shellcheck disable=SC1091
[ -f /etc/arch-release ] || error this script only works on Arch Linux

# make sure a valid domain name was provided (this isn't perfect validation, but it's good enough to check that it's not
# just garbage)
echo "$1" | grep -xEq '([0-9A-Za-z\-]+\.)+[0-9A-Za-z]+' || error you must provide a valid domain name as the first command-line argument

whoami | grep -xFq root || error you must run this script as root

# check for apparmor kernel parameter TODO
# [ -e /sys/kernel/security/apparmor/profiles ] || error you must enable apparmor in the kernel - see 'https://wiki.archlinux.org/index.php/AppArmor'

# install dependencies
# - base-devel: to install libcgroup
# - bubblewrap: primary sandboxing mechanism
# - certbot: generate SSL certificates for nginx
# - cronie: automate renewal of certbot certificates, cache cleaning, etc.
# - fuse-overlayfs: union filesystem
# - docker: to extract images of the various languages
# - git: to download libcgroup
# - nginx: web server
# - nginx-mod-modsecurity: web application firewall
# - python: runtime for API
# - sed: configuration editing on installation
# - sudo: privilege management for sandboxing
# - zsh: for running the runner scripts
pacman -Syu --noconfirm --needed \
    base-devel \
    bubblewrap \
    certbot \
    cronie \
    docker \
    git \
    nginx \
    nginx-mod-modsecurity \
    python \
    sed \
    sudo \
    zsh

# don't use /tmp because it has weird permissions
mkdir -p /var/cache/ATO

if [ "$ATO_MANUAL_PACKAGE" ]; then
    tar -xf "$ATO_MANUAL_PACKAGE" -C /var/cache/ATO
else
    curl -sSL "https://github.com/attempt-this-online/attempt-this-online/releases/download/v$VERSION/attempt_this_online.tar.gz" \
        | tar -xz -C /var/cache/ATO
fi

cd /var/cache/ATO

# install libcgroup
git clone https://aur.archlinux.org/libcgroup.git
# makepkg doesn't allow running as root, so use `nobody`
chown -R nobody:nobody libcgroup
cd libcgroup
sudo -u nobody makepkg --skippgpcheck
pacman -U --noconfirm --needed libcgroup-*.pkg.tar.zst
cd ../attempt_this_online

mkdir -p \
    /usr/local/lib/ATO \
    /usr/local/share/ATO

# configure ATO user
useradd -rs /usr/bin/nologin -md /var/lib/ATO_home ato

# install backend
install -m 500 -o ato -g ato server /usr/local/lib/ATO/

# install runners
cp -RT runners /usr/local/share/ATO/runners
chown -R ato:ato /usr/local/share/ATO/runners
chmod -R a+rX-w /usr/local/share/ATO/runners

# setup apparmor TODO
# systemctl enable --now apparmor.service

install -m 500 -o ato -g ato sandbox /usr/local/bin/ATO_sandbox
install -m 500 -o ato -g ato wrapper /usr/local/bin/ATO_wrapper

# install static files
cp -RT public /usr/local/share/ATO/public
for format in woff woff2 ttf; do
    curl "https://raw.githubusercontent.com/tonsky/FiraCode/master/distr/$format/FiraCode-Regular.$format" -o "/usr/local/share/ATO/public/FiraCode-Regular.$format"
done
for format in woff woff2 otf; do
    for variant in Bold Regular; do
        curl -L "https://github.com/pxeger/Cantarell/raw/v0.301-2/Cantarell$variant.$format" -o "/usr/local/share/ATO/public/Cantarell-$variant.$format"
    done
done
chown -R http:http /usr/local/share/ATO/public
chmod -R a+rX-w /usr/local/share/ATO/public

# configure nginx
sed -i "s/ato.pxeger.com/$1/g" setup/nginx.conf
install -m 644 -o root -g root setup/nginx.conf /etc/nginx/
install -m 644 -o root -g root setup/modsecurity.conf /etc/nginx/
# don't waste time generating DH params unless necessary
[ -f /etc/nginx/dhparam.pem ] || openssl dhparam -out /etc/nginx/dhparam.pem 2048
systemctl enable nginx.service

# configure Let's Encrypt
install -dm 750 -o root -g http /var/www/_letsencrypt
# we can't start nginx because the certificate isn't there, but we can't obtain a certificate if nginx isn't running
# so start a temporary Python web server
# TODO(pxeger): work around for letsencrypt issues without needing a temp Python server (certbot standalone mode?)
python -m http.server --directory /var/www/_letsencrypt 80 & PYSERVERPID="$!"
# TODO get option for email
certbot certonly -n --webroot -w /var/www/_letsencrypt -d "$1" -d "www.$1" --agree-tos --register-unsafely-without-email
# end that Python web server
kill -TERM "$PYSERVERPID"
# configure cronie to automatically renew certificates
# (every day at 10:07)
echo "7 10 * * * certbot renew && systemctl reload nginx" >> /var/spool/cron/root
systemctl enable --now cronie.service

# install yargs
install -m 555 -o root -g root yargs /usr/local/bin/ATO_yargs

# steal a statically linked bash from Debian
systemctl start docker.service
docker run --rm debian bash -c '{ apt-get update; apt-get install bash-static; } >/dev/null 2>&1; cat /bin/bash-static' > /usr/local/bin/ATO_bash
chown root:root /usr/local/bin/ATO_bash
chmod 555 /usr/local/bin/ATO_bash
systemctl stop docker.service

# configure service
install -m 555 -o root -g root setup/ATO /usr/local/bin/
mkdir -p /usr/local/lib/systemd/system/
install -m 644 -o root -g root setup/ATO.service /usr/local/lib/systemd/system/
systemctl enable ATO.service

# generate flags to be used as proof of compromise
flag() {
    tr < /dev/urandom -dc a-z | head -c 32 > "$1"
    chown "$2" "$1"
    chmod 400 "$1"
}
flag /root/flag root:root
flag /var/lib/ATO_home/flag ato:ato

# Create upper layer filesystem for overlayfs which contains the mount point /ATO pre-made for bwrap - see
# https://github.com/containers/bubblewrap/issues/413
mkdir -p /usr/local/share/ATO/overlayfs_upper/ATO /usr/local/share/ATO/overlayfs_upper/proc /usr/local/share/ATO/overlayfs_upper/dev

echo Finished system setup.
echo Now extracting Docker images - this will take a long time...

systemctl start docker.service

mkdir -p /usr/local/lib/ATO/env
mkdir -p /var/cache/ATO/images
while read -r image
do
    # ignore blank lines or comments
    [ -z "$image" ] || [ "$image" = "#" ] && continue
    echo "$image"
    # replace slash with plus so that it can be used as an individual filename
    image_pathsafe="$(echo "$image" | tr '/' '+')"
    docker pull "$image"
    docker save "$image" | tar -xC /var/cache/ATO/images
    mv /var/cache/ATO/images/manifest.json "/var/cache/ATO/images/manifest_$image_pathsafe.json"
    # extract environment variables from the image
    docker image inspect -f '{{json .Config.Env}}' "$image" | setup/parse_env > "/usr/local/lib/ATO/env/$image_pathsafe"
done < images.txt

# shellcheck disable=SC2010
ls /var/cache/ATO/images | 
grep -Ex '[0-9a-f]+' |
    while read -r layer
    do
        mkdir -p "/usr/local/lib/ATO/layers/$layer"
        tar -xf "/var/cache/ATO/images/$layer/layer.tar" -C \
            "/usr/local/lib/ATO/layers/$layer"
        rm "/var/cache/ATO/images/$layer/layer.tar"
    done

# shellcheck disable=SC2010
ls /var/cache/ATO/images |
grep -Ex 'manifest_.+\.json' |
    while read -r manifest
    do
        setup/overlayfs_genfstab "$manifest" >> /etc/fstab
    done

echo Finished extracting images.
echo Clearing up...

systemctl disable --now docker.service docker.socket
cd /

echo Starting up services...
# mount all overlayfs
mount -a
systemctl start nginx.service ATO.service

echo Finished!
