#!/bin/sh

systemctl disable --now ATO.service nginx.service
sed -i '/^overlay/d' /etc/fstab
sed -i '/certbot renew && systemctl reload nginx/d' /var/spool/cron/root
umount /usr/local/lib/ATO/rootfs/*
userdel ato
rm -rf \
    /var/cache/ATO \
    /var/lib/ATO_home \
    /usr/local/lib/ATO \
    /usr/local/share/ATO \
    /usr/local/bin/ATO \
    /usr/local/bin/ATO_yargs \
    /usr/local/bin/ATO_bash \
    /usr/local/bin/ATO_invoke \
    /usr/local/lib/systemd/system/ATO.service \
    /usr/local/lib/systemd/system/ATO.socket
