#!/bin/sh

systemctl disable --now ATO.service nginx.service
sed -i '/^overlay/d' /etc/fstab
sed -i '/certbot renew && systemctl reload nginx/d' /var/spool/cron/root
umount /usr/local/lib/ATO/rootfs/*
pkill -9 uvicorn
userdel api
userdel sandbox
rm -rf \
    /var/cache/ATO \
    /run/lock/ATO \
    /var/lib/ATO_home \
    /usr/local/lib/ATO \
    /usr/local/share/ATO \
    /usr/local/bin/ATO_run \
    /usr/local/bin/ATO_sandbox \
    /etc/sudoers.d/40_ATO \
    /usr/local/lib/systemd/system/ATO.service \
    /usr/local/lib/systemd/system/ATO.socket
