#!/bin/sh
#:name: Bash
#:image: attemptthisonline/bash
#:version: Latest
#:url: https://www.gnu.org/software/bash/
#:sbcs: false
#:SE_class: bash

cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments /usr/local/bin/bash %1 /ATO/code %2 < /ATO/input
