#!/bin/sh

cd /ATO/context
mkdir /ATO/tmp
export TMPDIR=/ATO/tmp
ln -s /ATO/code /ATO/code.c
/ATO/yargs % /ATO/options clang % /ATO/code.c -o /ATO/exe
/ATO/yargs % /ATO/arguments /ATO/exe % < /ATO/input
