#!/bin/sh

cd /ATO/context
# dyalogscript requires a trailing newline at the end of the file, otherwise it won't read the last line
echo >>/ATO/code
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments dyalogscript %1 /ATO/code %2 </ATO/input
