#!/bin/sh

cd /ATO/context
{
    printf %s f
    if [ "$(wc -c < /ATO/options)" -eq 0 ]; then
        printf '\0'
    else
        cat /ATO/options
    fi
} > /ATO/options2
/ATO/yargs %1 /ATO/options2 /ATO/yargs %2 /ATO/arguments python -m flax %1 /ATO/code %2 < /ATO/input
