#!/bin/sh

cd /ATO/context
cp /opt/go.mod /opt/go.sum /ATO/
ln -s /ATO/code /ATO/code.go
mkdir /ATO/tmp
export TMPDIR=/ATO/tmp GOCACHE=/ATO/tmp
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments go run %1 /ATO/code.go %2 < /ATO/input
