#!/bin/sh
#:name: Jelly
#:image: attemptthisonline/jelly:commit-70c9fd93
#:version: 0.1.30
#:url: https://github.com/DennisMitchell/jellylanguage
#:sbcs: true

mkdir /ATO/tmp
export TMPPREFIX=/ATO/tmp

cd /ATO/context

/ATO/yargs % /ATO/arguments /usr/local/bin/jelly fun /ATO/code % < /ATO/input
