#!/bin/sh

cd /ATO/context
ln -s /ATO/code /ATO/code.nim
mkdir /ATO/cache
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments /opt/nim/bin/nim r --nimcache:/ATO/cache %1 /ATO/code.nim %2 < /ATO/input
