#!/bin/sh
#:name: Pip
#:image: attemptthisonline/pip
#:version: Latest
#:url: https://github.com/dloscutoff/pip
#:sbcs: false

cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments piplang %1 /ATO/code %2 < /ATO/input
