#!/bin/sh
#:name: Python
#:image: attemptthisonline/python
#:version: Latest
#:url: https://www.python.org
#:sbcs: false
#:SE_class: python

cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments python %1 /ATO/code %2 < /ATO/input
