#!/bin/sh
#:name: Python
#:image: python:3-buster
#:version: Latest
#:url: https://docs.python.org/3/
#:sbcs: false

cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments python %1 /ATO/code %2 < /ATO/input
