#!/bin/sh

cd /ATO/context

mkdir /ATO/tmp
export TMPDIR=/ATO/tmp
export CARGO_HOME=/ATO/tmp

/ATO/yargs % /ATO/options rustc % /ATO/code -o /ATO/exe
/ATO/yargs % /ATO/arguments /ATO/exe % < /ATO/input
