#!/bin/sh
#:name: Scala
#:image: hseeberger/scala-sbt:16.0.2_1.5.5_2.13.6
#:version: 2
#:url: https://www.scala-lang.org/
#:sbcs: false
#:SE_class: scala

mkdir /ATO/tmp
cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments /usr/local/bin/scala -Djava.io.tmpdir=/ATO/tmp %1 /ATO/code %2 < /ATO/input
