#!/bin/sh
#:name: Scala
#:image: attemptthisonline/scala
#:version: 2.13.6
#:url: https://www.scala-lang.org/
#:sbcs: false

cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments /usr/local/bin/scala %1 /ATO/code %2 < /ATO/input
