#!/bin/sh

mkdir /ATO/tmp
cd /ATO/context
ln -s /ATO/code /ATO/code.scala
export JAVA_OPTS=-Djava.io.tmpdir=/ATO/tmp
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments scala %1 /ATO/code.scala %2 < /ATO/input
