#!/bin/sh
#:name: Whython
#:image: attemptthisonline/whython
#:version: Latest
#:url: https://github.com/pxeger/whython
#:sbcs: false
#:SE_class: python

cd /ATO/context
/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments python %1 /ATO/code %2 < /ATO/input
