#!/bin/sh
#:name: Zsh
#:image: attemptthisonline/zsh:5.8

mkdir /ATO/tmp
export TMPPREFIX=/ATO/tmp

cd /ATO/context

/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments /usr/local/bin/zsh %1 /ATO/code %2 < /ATO/input
