#!/bin/sh
#:name: Zsh
#:image: attemptthisonline/zsh
#:version: 5
#:url: https://www.zsh.org/
#:sbcs: false
#:SE_class: bash

mkdir /ATO/tmp
export TMPPREFIX=/ATO/tmp

cd /ATO/context

/ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments zsh %1 /ATO/code %2 < /ATO/input
